# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_m2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Module2(object):
    def setupUi(self, Module2):
        Module2.setObjectName("Module2")
        Module2.resize(340, 720)
        self.centralwidget = QtWidgets.QWidget(Module2)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 8, 320, 660))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_scan = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_scan.setGeometry(QtCore.QRect(110, 80, 100, 28))
        self.pushButton_scan.setObjectName("pushButton_scan")
        self.label_rm = QtWidgets.QLabel(self.groupBox)
        self.label_rm.setGeometry(QtCore.QRect(10, 200, 300, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(False)
        font.setWeight(50)
        self.label_rm.setFont(font)
        self.label_rm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_rm.setObjectName("label_rm")
        Module2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Module2)
        self.statusbar.setObjectName("statusbar")
        Module2.setStatusBar(self.statusbar)

        self.retranslateUi(Module2)
        QtCore.QMetaObject.connectSlotsByName(Module2)

    def retranslateUi(self, Module2):
        _translate = QtCore.QCoreApplication.translate
        Module2.setWindowTitle(_translate("Module2", "Module2"))
        self.groupBox.setTitle(_translate("Module2", "Bank Note Recognition Module"))
        self.pushButton_scan.setText(_translate("Module2", "Scan"))
        self.label_rm.setText(_translate("Module2", "Text Here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Module2 = QtWidgets.QMainWindow()
    ui = Ui_Module2()
    ui.setupUi(Module2)
    Module2.show()
    sys.exit(app.exec_())
